name: Scrape Moneycontrol

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          pip install google-api-python-client google-auth google-auth-oauthlib
          playwright install chromium

      - name: Run scraper
        run: python new.py  # ✅ FIXED LINE
