name: Run Playwright Scraper

on:
  workflow_dispatch:  # Allows you to run manually from GitHub
  push:
    branches:
      - main  # Or any branch you use

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python scrape.py

      - name: Upload Debug Artifacts (if needed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            *.html
            *.png
