name: Run Scraper

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 6 * * *'  # runs daily at 6:00 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run scraper
        run: |
          python scrape_reports.py
